### ISSUE TITLE
Ref: JAR roadRunner

### ISSUE THREAD

**Issue by skAutomation12** [RationaleEmotions/cucumber-roadrunner#2]
Hello Krishnan, 

How do i download the JAR; as I would need to provide that the my team to use it in my company.

**Comment by krmahadevan** [comment]
It's published to Maven central. So you just need to add a dependency to it in your pom file and then use. Details are available in the README.md file.

**Comment by skAutomation12** [comment]
Sir there are 4 instances in maven Central. I would highly appreciate if
you could send me the URL to download it. To use with intranet.. I would
have to setup the jar. Can't go outside network to access maven Central.

**Comment by krmahadevan** [comment]
@skAutomation12 - Ok, sounds like you aren't familiar with how Maven works.

When it comes to SNAPSHOT dependency consumption, here's some general information

In the URL https://oss.sonatype.org/content/repositories/snapshots/com/rationaleemotions/roadrunner/1.0.0-SNAPSHOT/
open up the `maven-metadata.xml`.
In that file the section 

```xml
<snapshot>
<timestamp>20180407.081406</timestamp>
<buildNumber>2</buildNumber>
</snapshot>
```
will tell you the latest published `buildNumber`. In this case `2`.

So in the afore-mentioned URL, you look for a jar whose name contains `-2`.

That would be `https://oss.sonatype.org/content/repositories/snapshots/com/rationaleemotions/roadrunner/1.0.0-SNAPSHOT/roadrunner-1.0.0-20180407.081406-2.jar`

PS: Merely downloading this jar manually on your own, will not work. You would need to get all the dependencies that have been called out in the pom file. 

So I would strongly advise you to have maven do the job for you.

If you have an intranet Maven repository (typically companies do that), then you should have your DevOps team mirror this library into your intranet maven repository.
